/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#95d4b3",
        "surface-tint": "#545f73",
        "surface-container-low": "#f2f4f6",
        "surface": "#f7f9fb",
        "on-secondary-fixed-variant": "#0e5138",
        "on-tertiary-fixed": "#00201d",
        "on-primary-fixed": "#111c2d",
        "on-tertiary-container": "#28a094",
        "error": "#ba1a1a",
        "on-background": "#191c1e",
        "outline": "#75777d",
        "surface-container-high": "#e6e8ea",
        "on-tertiary": "#ffffff",
        "tertiary-fixed-dim": "#6bd8cb",
        "on-primary-container": "#8590a6",
        "primary-fixed": "#d8e3fb",
        "outline-variant": "#c5c6cd",
        "inverse-surface": "#2d3133",
        "tertiary-container": "#002f2a",
        "on-error": "#ffffff",
        "tertiary": "#001815",
        "surface-container": "#eceef0",
        "tertiary-fixed": "#89f5e7",
        "primary": "#091426",
        "on-primary": "#ffffff",
        "on-secondary-container": "#316e52",
        "secondary": "#2c694e",
        "on-error-container": "#93000a",
        "on-surface-variant": "#45474c",
        "surface-bright": "#f7f9fb",
        "on-tertiary-fixed-variant": "#005049",
        "on-secondary-fixed": "#002114",
        "error-container": "#ffdad6",
        "surface-variant": "#e0e3e5",
        "surface-container-highest": "#e0e3e5",
        "secondary-container": "#aeeecb",
        "inverse-on-surface": "#eff1f3",
        "on-secondary": "#ffffff",
        "primary-container": "#1e293b",
        "on-surface": "#191c1e",
        "surface-dim": "#d8dadc",
        "on-primary-fixed-variant": "#3c475a",
        "background": "#f7f9fb",
        "secondary-fixed": "#b1f0ce",
        "inverse-primary": "#bcc7de",
        "primary-fixed-dim": "#bcc7de",
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
      },
      spacing: {
        "margin-mobile": "1rem",
        "stack-md": "1rem",
        "stack-lg": "2rem",
        "sidebar-width": "260px",
        "container-max": "1440px",
        "margin-desktop": "2rem",
        "gutter": "1.5rem",
        "stack-sm": "0.5rem",
      },
      fontFamily: {
        "label-caps": ["Inter", "sans-serif"],
        "data-mono": ["JetBrains Mono", "monospace"],
        "body-sm": ["Inter", "sans-serif"],
        "body-lg": ["Inter", "sans-serif"],
        "headline-md": ["Inter", "sans-serif"],
        "body-md": ["Inter", "sans-serif"],
        "headline-sm": ["Inter", "sans-serif"],
        "headline-lg": ["Inter", "sans-serif"],
      },
    },
  },
  plugins: [],
}
